### ISSUE TITLE
Weird artifact

### ISSUE THREAD

**Issue by davelab6** [graphicore/mdlFontSpecimen#1]
![screen shot 2016-11-02 at 16 15 45](https://cloud.githubusercontent.com/assets/261579/19945686/a0c14d1e-a117-11e6-92ba-7e2432cce451.png)

What is `🡻` doing there? :)

**Comment by graphicore** [comment]
I'm sorry that I have to bring it to you, but your system sucks at unicode! What was it again? Mac OS 10?

should be like this:

![selection_115](https://cloud.githubusercontent.com/assets/393132/19952146/5a05abe4-a163-11e6-9e5d-6ffef8897998.png)

It's "WIDE-HEADED DOWNWARDS HEAVY BARB ARROW", u1F87B

But I agree that we have to do something there :-)

**Comment by davelab6** [comment]
Can you use Material icons for this?

Yep is os x 10.11

**Comment by graphicore** [comment]
The Material Icons font was already included. Thanks for the hint :-)

![selection_116](https://cloud.githubusercontent.com/assets/393132/19966284/61970138-a1cb-11e6-85a1-5601ccc6a353.png)

**Comment by alexeiva** [comment]
@davelab6 has beat me. I wanted to post the exact same image here :)

<img width="304" alt="screen shot 2016-11-02 at 14 34 03" src="https://cloud.githubusercontent.com/assets/16634089/19992683/62f494fa-a216-11e6-979e-f22ebdbd0352.png">

**Comment by graphicore** [comment]
@alexeiva it should be fixed already. Is the image current?

**Comment by alexeiva** [comment]
it is fixed now.
